version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "07:07"
    timezone: America/Los_Angeles
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: husky
    versions:
    - ">= 6.a, < 7"
  - dependency-name: xo
    versions:
    - 0.38.2
    - 0.39.1
  - dependency-name: postcss
    versions:
    - 8.2.10
    - 8.2.12
    - 8.2.6
    - 8.2.7
    - 8.2.8
    - 8.2.9
  - dependency-name: rollup
    versions:
    - 2.38.0
    - 2.38.1
    - 2.38.5
    - 2.39.0
    - 2.40.0
    - 2.41.2
    - 2.42.1
    - 2.43.0
    - 2.44.0
    - 2.45.1
    - 2.45.2
  - dependency-name: "@types/jest"
    versions:
    - 26.0.21
    - 26.0.22
  - dependency-name: eslint
    versions:
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.14.1
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
    - 4.22.0
  - dependency-name: husky
    versions:
    - 5.0.9
    - 5.1.1
    - 5.1.3
    - 5.2.0
  - dependency-name: typescript
    versions:
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: ts-jest
    versions:
    - 26.5.0
    - 26.5.1
    - 26.5.2
    - 26.5.3
  - dependency-name: rollup-plugin-typescript2
    versions:
    - 0.30.0
  - dependency-name: check-node-version
    versions:
    - 4.1.0
  - dependency-name: lint-staged
    versions:
    - 10.5.4
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.27
  - dependency-name: autoprefixer
    versions:
    - 10.2.3
    - 10.2.4
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.14.1
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
    - 4.22.0
  - dependency-name: "@rollup/plugin-node-resolve"
    versions:
    - 11.1.1
    - 11.2.1
  - dependency-name: "@typescript-eslint/typescript-estree"
    versions:
    - 4.14.1
